version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: drafty-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drafty
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - drafty-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: drafty-backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/drafty
      NODE_ENV: development
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/prisma/generated
    networks:
      - drafty-network
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

volumes:
  postgres-data:

networks:
  drafty-network:
    driver: bridge